executor: go-machine
parallelism: 10
steps:
  - checkout
  - run:
      name: Allow circleci user to restore Go modules cache
      command: |
        set -eux -o pipefail
        sudo mkdir /go
        sudo chown -R circleci:circleci /go
  - restore_go_cache
  - make-test-sample:
      TESTARGS: -v
      OUTDIR: sample/make-test
