executor: docker-env
parallelism: 8
steps:
  - check-branch-name
  - setup-go
  - checkout
  - setup_remote_docker:
      docker_layer_caching: true
  - go_test:
      log_dir: "/tmp/testlogs"
  - store_artifacts:
      path: test-results
  - store_test_results:
      path: test-results
  - store_artifacts:
      path: "/tmp/testlogs"
