
workflows:
  build-release:
    jobs:
      - cache-builder-images
      - build_darwin_386: { requires: [ cache-builder-images ] }
      - build_darwin_amd64: { requires: [ cache-builder-images ] }
      - build_freebsd_386: { requires: [ cache-builder-images ] }
      - build_freebsd_amd64: { requires: [ cache-builder-images ] }
      - build_freebsd_arm: { requires: [ cache-builder-images ] }
      - build_linux_386: { requires: [ cache-builder-images ] }
      - build_linux_amd64: { requires: [ cache-builder-images ] }
      - build_linux_arm: { requires: [ cache-builder-images ] }
      - build_linux_arm64: { requires: [ cache-builder-images ] }
      - build_netbsd_386: { requires: [ cache-builder-images ] }
      - build_netbsd_amd64: { requires: [ cache-builder-images ] }
      - build_openbsd_386: { requires: [ cache-builder-images ] }
      - build_openbsd_amd64: { requires: [ cache-builder-images ] }
      - build_solaris_amd64: { requires: [ cache-builder-images ] }
      - build_windows_386: { requires: [ cache-builder-images ] }
      - build_windows_amd64: { requires: [ cache-builder-images ] }
      - bundle-releases:
          requires:
            - build_darwin_386
            - build_darwin_amd64
            - build_freebsd_386
            - build_freebsd_amd64
            - build_freebsd_arm
            - build_linux_386
            - build_linux_amd64
            - build_linux_arm
            - build_linux_arm64
            - build_netbsd_386
            - build_netbsd_amd64
            - build_openbsd_386
            - build_openbsd_amd64
            - build_solaris_amd64
            - build_windows_386
            - build_windows_amd64
jobs:
  cache-builder-images:
    executor: releaser
    steps:
      - setup_remote_docker
      - checkout
      - ensure-builder-image-cache
  bundle-releases:
    executor: releaser
    steps:
      - checkout
      - load-packages
      - run: ls -lahR dist/
