---
workflows:
  build-release:
    jobs:
      - make-static-builder

jobs:
  make-static-builder:
    executor: releaser
    steps:
      - checkout
      - build-base-restore
      - build-ui-deps-restore
      - build-static-restore
      - run: make -f release.Makefile base-archive
      - run: make -f release.Makefile ui-deps-archive
      - run: make -f release.Makefile static-archive
      - build-base-save
      - build-ui-deps-save
      - build-static-save
  build-darwin-amd64:
    executor: releaser
    environment:
      GOOS: darwin
      GOARCH: amd64
    steps:
      - checkout
      - build-static-restore
      - run: make -f release.Makefile package

