---
workflows:
  build-release:
    jobs:
      - cache-builder-images
      - build-darwin-amd64: { requires: [ cache-builder-images ] }
      - build-linux-386: { requires: [ cache-builder-images ] }
      - build-darwin-amd64: { requires: [ cache-builder-images ] }
      - build-darwin-386: { requires: [ cache-builder-images ] }

jobs:
  cache-builder-images:
    executor: releaser
    steps:
      - setup_remote_docker
      - checkout
      - ensure-builder-image-cache
