---
workflows:
  build-release:
    jobs:
      - cache-builder-images
      - build-linux-amd64: { requires: [ cache-builder-images ] }
      - build-linux-386: { requires: [ cache-builder-images ] }
      - build-darwin-amd64: { requires: [ cache-builder-images ] }
      - build-darwin-386: { requires: [ cache-builder-images ] }
      - bundle-releases:
          requires:
            - build-linux-amd64
            - build-linux-386
            - build-darwin-amd64
            - build-darwin-386


jobs:
  cache-builder-images:
    executor: releaser
    steps:
      - setup_remote_docker
      - checkout
      - ensure-builder-image-cache
  bundle-releases:
    executor: releaser
    steps:
      - checkout
      - load-packages
      - run: ls -lahR dest/
