ensure-builder-image-cache:
  description: >
    Ensure all intermediate build images are cached appropriately.
    Use this in an earlier job than ensure-static-builder to make sure
    all builder caches are up to date. Because we specifically build
    each image archive here, we can be sure they are restorable.
  steps:
    - restore-each-builder-cache
    - run: make -f release.Makefile base-archive
    - run: make -f release.Makefile ui-deps-archive
    - run: make -f release.Makefile static-archive
    - save-builder-cache

ensure-static-builder:
  description: >
    Ensures the static builder image is available (prefers cache but will rebuild it if necessary).
    Use this to prepare the builder for building final packages.
  steps:
    - restore-builder-cache

restore-each-builder-cache:
  description: >
    Restore each separate cached archive so we can just update those layers that need it.
  steps:
    - write-builder-cache-keys
    - restore_cache:
        key: &BASE_CACHE_KEY base-archive-v1-{{ checksum ".buildcache/base-cache-key" }}
    - restore_cache:
        key: &UI_DEPS_CACHE_KEY ui-deps-archive-v1-{{ checksum ".buildcache/ui-deps-cache-key" }}
    - restore_cache:
        key: &STATIC_CACHE_KEY static-archive-v1-{{ checksum ".buildcache/static-cache-key" }}
    - info-print-buildcache

restore-builder-cache:
  description: >
    Just restore the most specific cache that exists, not intermediate caches.
    This is what you need to build packages.
  steps:
    - write-builder-cache-keys
    - restore_cache:
        keys:
          - *STATIC_CACHE_KEY
          - *UI_DEPS_CACHE_KEY
          - *BASE_CACHE_KEY
    - info-print-buildcache
    - run:
        name: Restore static builder image (or best available).
        command: |
          make -f release.Makefile static-restore || \
          make -f release.Makefile ui-deps-restore || \
          make -f release.Makefile base-restore || \
          echo "Unable to restore an builder images, rebuilding from scratch."

write-builder-cache-keys:
  steps:
    - write-cache-key:
        layer-name: static
    - write-cache-key:
        layer-name: ui-deps
    - write-cache-key:
        layer-name: base

save-builder-cache:
  steps:
    - write-builder-cache-keys
    - info-print-buildcache
    - save_cache:
        key: *BASE_CACHE_KEY
        paths:
          - .buildcache/base
    - save_cache:
        key: *UI_DEPS_CACHE_KEY
        paths:
          - .buildcache/ui-deps
    - save_cache:
        key: *STATIC_CACHE_KEY
        paths:
          - .buildcache/static

info-print-buildcache:
  steps:
    - run:
        name: Info - list files in .buildcache/
        command: |
          ls -lahR .buildcache

write-cache-key:
  parameters:
    layer-name:
      type: string
  steps:
    - run:
        name: Generate <<parameters.layer-name>> image cache key.
        environment:
          NAME: <<parameters.layer-name>>
        command: |
          mkdir -p .buildcache
          FILE=.buildcache/$NAME-cache-key
          make -f release.Makefile $NAME-archive-name > $FILE
          echo "Cache key for layer '$NAME' is $(cat $FILE); written to $FILE"

build-package:
  parameters:
    GOOS:
      type: string
    GOARCH:
      type: string
    EDITION:
      type: string
      default: ""
  steps:
    - setup_remote_docker
    - checkout
    - ensure-static-builder
    - run:
        name: Compile package
        environment:
          GOOS: "<<parameters.GOOS>>"
          GOARCH: "<<parameters.GOARCH>>"
          EDITION: "<<parameters.EDITION>>"
        command: |
          make -f release.Makefile package
    - store_artifacts:
        path: dest/
        destination: dest
    - write-builder-cache-keys
    - save_cache:
        key: package-<<parameters.EDITION>>_<<parameters.GOOS>>_<<parameters.GOARCH>>-cache-v1-{{ checksum ".buildcache/static-cache-key" }}
        paths:
          - dist/
