write-base-cache-key:
  steps:
    - run:
        name: Generate base image cache key.
        command: |
          mkdir -p .buildcache
          make -f release.Makefile base-archive-name > .buildcache/base-cache-key
build-base-restore:
  steps:
    - write-base-cache-key
    - restore_cache:
        key: base-archive-v1-{{ checksum ".buildcache/base-cache-key" }}
    - run: ls -lahR .buildcache
    - run: make -f release.Makefile base-restore
build-base-save:
  steps:
    - write-base-cache-key
    - save_cache:
        key: base-archive-v1-{{ checksum ".buildcache/base-cache-key" }}
        paths:
          - .buildcache/base
write-ui-deps-cache-key:
  steps:
    - run:
        name: Generate ui-deps image cache key.
        command: |
          mkdir -p .buildcache
          make -f release.Makefile ui-deps-archive-name > .buildcache/ui-deps-cache-key
build-ui-deps-restore:
  steps:
    - write-ui-deps-cache-key
    - restore_cache:
        key: ui-deps-archive-v1-{{ checksum ".buildcache/ui-deps-cache-key" }}
    - run: ls -lahR .buildcache
    - run: make -f release.Makefile ui-deps-restore
build-ui-deps-save:
  steps:
    - write-ui-deps-cache-key
    - save_cache:
        key: ui-deps-archive-v1-{{ checksum ".buildcache/ui-deps-cache-key" }}
        paths:
          - .buildcache/ui-deps
write-static-cache-key:
  steps:
    - run:
        name: Generate static image cache key.
        command: |
          mkdir -p .buildcache
          make -f release.Makefile static-archive-name > .buildcache/static-cache-key
build-static-restore:
  steps:
    - write-static-cache-key
    - restore_cache:
        key: static-archive-v1-{{ checksum ".buildcache/static-cache-key" }}
    - run: ls -lahR .buildcache
    - run: make -f release.Makefile static-restore
build-static-save:
  steps:
    - write-static-cache-key
    - save_cache:
        key: static-archive-v1-{{ checksum ".buildcache/static-cache-key" }}
        paths:
          - .buildcache/static
