description: run go tests
parameters:
  extra_flags:
    type: string
    default: ""
  CGO_ENABLED:
    type: integer
    default: 0
steps:
  - run:
      name: Run Go tests
      no_output_timeout: 20m
      command: |
        set -eux -o pipefail

        # Install Go
        curl -sSLO "https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz"
        sudo rm -rf /usr/local/go
        sudo tar -C /usr/local -xzf "go${GO_VERSION}.linux-amd64.tar.gz"
        rm -f "go${GO_VERSION}.linux-amd64.tar.gz"
        export GOPATH=/go
        export PATH="${PATH}:${GOPATH}/bin:/usr/local/go/bin"

        # Run tests
        export TESTARGS="<< parameters.extra_flags >>"
        export CGO_ENABLED="<< parameters.extra_flags >>"
        make test

