jobs:
  - install-ui-dependencies
  - go-mod-download
  - build-go-dev:
      requires:
        - go-mod-download
  - test-ui:
      requires:
        - install-ui-dependencies
        - build-go-dev
  - test-go:
      requires:
        - build-go-dev
  - test-go-race:
      requires:
        - build-go-dev
  # The report-success job depends only on the _required_ jobs that indicate success.
  # This allows us to ignore certain jobs that are works in progress at the moment.
  - report-success:
      requires:
        - test-ui
        - test-go
